import os
import json
import httpx
from typing import Optional, Dict, Any, List

DEFAULT_MODEL = os.getenv("GEMINI_MODEL", "gemini-1.5-flash")

def _get_api_key(api_key: Optional[str] = None) -> Optional[str]:
    return api_key or os.getenv("GEMINI_API_KEY")

async def _call_gemini(prompt: str, system_prompt: str = "You are an expert data analyst and business intelligence consultant.", api_key: Optional[str] = None, model: str = DEFAULT_MODEL) -> str:
    key = _get_api_key(api_key)
    if not key:
        return "Gemini API key not configured. Please add GEMINI_API_KEY to your .env or enter it in the UI."
    
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={key}"
    
    headers = {
        "Content-Type": "application/json"
    }
    
    payload = {
        "system_instruction": {
            "parts": [{"text": system_prompt}]
        },
        "contents": [{
            "parts": [{"text": prompt}]
        }],
        "generationConfig": {
            "temperature": 0.3
        }
    }
    
    async with httpx.AsyncClient(timeout=60.0) as client:
        try:
            response = await client.post(url, headers=headers, json=payload)
            response.raise_for_status()
            data = response.json()
            if "candidates" in data and len(data["candidates"]) > 0:
                return data["candidates"][0]["content"]["parts"][0]["text"]
            return "No response generated by Gemini."
        except Exception as e:
            return f"Error connecting to Gemini API: {str(e)}"

async def generate_insights(dataset_summary: dict, columns_meta: list, insights_meta: list, user_prompt: Optional[str] = None, api_key: Optional[str] = None) -> str:
    system_prompt = "You are a senior data analyst. Extract high-value executive observations, business risks, data quality recommendations, and anomalies from the provided dataset metadata."
    
    prompt = f"""
Dataset Summary:
{json.dumps(dataset_summary, indent=2)}

Column Metadata:
{json.dumps(columns_meta, indent=2)}

Initial Statistical Insights:
{json.dumps(insights_meta, indent=2)}

"""
    if user_prompt:
        prompt += f"User context / request: {user_prompt}\n\n"
        
    prompt += "Please provide a concise, structured response with bullet points highlighting key insights, risks, and recommendations."
    
    return await _call_gemini(prompt, system_prompt, api_key)

async def generate_eda_advice(eda_summary: dict, api_key: Optional[str] = None) -> str:
    system_prompt = "You are an expert data engineer. Recommend an automated data cleaning and preprocessing strategy based on the data's anomalies, skewness, and missingness."
    
    prompt = f"""
EDA Summary:
{json.dumps(eda_summary, indent=2)}

Please suggest specific actions for missing value imputation, outlier handling, and column transformations.
"""
    return await _call_gemini(prompt, system_prompt, api_key)

async def generate_full_report(config: dict, dataset_meta: dict, trend_data: dict, forecast_data: dict, eda_meta: dict, api_key: Optional[str] = None) -> str:
    system_prompt = "You are an elite Business Intelligence consultant producing a comprehensive data report for stakeholders."
    
    prompt = f"""
Report Configuration:
{json.dumps(config, indent=2)}

Dataset Metadata:
{json.dumps(dataset_meta, indent=2)}

EDA & Quality Meta:
{json.dumps(eda_meta, indent=2)}
"""
    if trend_data:
        prompt += f"\nTrend Data:\n{json.dumps(trend_data, indent=2)}"
    if forecast_data:
        prompt += f"\nForecast Data:\n{json.dumps(forecast_data, indent=2)}"
        
    prompt += "\n\nSynthesize this into a structured, professional report following the requested sections. Use markdown formatting."
    
    return await _call_gemini(prompt, system_prompt, api_key)
