import os
import json
import httpx
from typing import Optional, Dict, Any, List

DEFAULT_MODEL = os.getenv("GEMINI_MODEL", "gemini-3.6-flash")

def _get_api_key(api_key: Optional[str] = None) -> Optional[str]:
    return api_key or os.getenv("GEMINI_API_KEY")

import re

def _clean_html(text: str) -> str:
    if not text:
        return ""
    text = text.strip()
    if text.startswith("```html"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    text = text.strip()
    # Strip any inline white or light text styling in tables or headers that breaks contrast
    text = re.sub(r'color\s*:\s*(#fff(fff)?|white|#f8fafc|#f1f5f9|#e2e8f0)', 'color: #0f172a', text, flags=re.IGNORECASE)
    text = re.sub(r'class=[\'"][^\'"]*text-white[^\'"]*[\'"]', '', text, flags=re.IGNORECASE)
    return text

async def _call_gemini(prompt: str, system_prompt: str = "You are an expert data analyst and business intelligence consultant.", api_key: Optional[str] = None, model: str = DEFAULT_MODEL) -> str:
    key = _get_api_key(api_key)
    if not key:
        return "<p class='text-amber-600'>⚠️ Gemini API key not configured. Please add GEMINI_API_KEY to your .env or enter it in the UI (Settings / Key icon).</p>"
    
    # Ensure active model is used
    if not model or model in ["gemini-2.0-flash", "gemini-1.5-flash", "gemini-2.5-flash", "gemini-3.1-pro"]:
        model = "gemini-3.6-flash"
    
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={key}"
    headers = {
        "Content-Type": "application/json"
    }
    
    payload = {
        "system_instruction": {
            "parts": [{"text": system_prompt}]
        },
        "contents": [{
            "parts": [{"text": prompt}]
        }],
        "generationConfig": {
            "temperature": 0.3
        }
    }
    
    async with httpx.AsyncClient(timeout=60.0) as client:
        try:
            response = await client.post(url, headers=headers, json=payload)
            if response.status_code != 200:
                try:
                    err_json = response.json()
                    err_msg = err_json.get("error", {}).get("message", response.text)
                except Exception:
                    err_msg = response.text or f"HTTP {response.status_code}"
                return f"<p class='text-red-500'><strong>Gemini API Error ({response.status_code}):</strong> {err_msg}</p>"
            
            data = response.json()
            if "candidates" in data and len(data["candidates"]) > 0:
                raw_text = data["candidates"][0]["content"]["parts"][0]["text"]
                return _clean_html(raw_text)
            return "<p>No response generated by Gemini.</p>"
        except httpx.RequestError as e:
            return f"<p class='text-red-500'><strong>Network Error:</strong> Could not connect to Gemini API ({str(e)})</p>"
        except Exception as e:
            return f"<p class='text-red-500'><strong>Error:</strong> {str(e)}</p>"

HTML_INSTRUCTION = """\nIMPORTANT: Format your entire response using clean, semantic HTML tags for rich web display. Use <h3> and <h4> for section headings, <ul>/<li> for bullet points, <ol>/<li> for numbered lists, <strong> for key takeaways, <table>/<thead>/<tbody>/<tr>/<td>/<th> for tabular comparisons (tables MUST have high-contrast dark text #0f172a and clean borders; NEVER use white or light text), <p> for paragraphs, and <span style='color:#dc2626'> for warnings or <span style='color:#16a34a'> for positive highlights. Do NOT output markdown backticks (e.g. ```html). Output raw HTML directly."""



async def generate_insights(dataset_summary: dict, columns_meta: list, insights_meta: list, user_prompt: Optional[str] = None, api_key: Optional[str] = None) -> str:
    system_prompt = "You are a senior data analyst. Extract high-value executive observations, business risks, data quality recommendations, and anomalies from the provided dataset metadata." + HTML_INSTRUCTION
    
    prompt = f"""
Dataset Summary:
{json.dumps(dataset_summary, indent=2)}

Column Metadata:
{json.dumps(columns_meta, indent=2)}

Initial Statistical Insights:
{json.dumps(insights_meta, indent=2)}

"""
    if user_prompt:
        prompt += f"User context / request: {user_prompt}\n\n"
        
    prompt += "Please provide a concise, structured response highlighting key insights, risks, and recommendations. Use HTML formatting."
    
    return await _call_gemini(prompt, system_prompt, api_key)

async def generate_eda_advice(eda_summary: dict, api_key: Optional[str] = None) -> str:
    system_prompt = "You are an expert data engineer. Recommend an automated data cleaning and preprocessing strategy based on the data's anomalies, skewness, and missingness." + HTML_INSTRUCTION
    
    prompt = f"""
EDA Summary:
{json.dumps(eda_summary, indent=2)}

Please suggest specific actions for missing value imputation, outlier handling, and column transformations. Use HTML formatting.
"""
    return await _call_gemini(prompt, system_prompt, api_key)

async def generate_full_report(config: dict, dataset_meta: dict, trend_data: dict, forecast_data: dict, eda_meta: dict, api_key: Optional[str] = None) -> str:
    system_prompt = "You are an elite Business Intelligence consultant producing a comprehensive data report for stakeholders." + HTML_INSTRUCTION
    
    prompt = f"""
Report Configuration:
{json.dumps(config, indent=2)}

Dataset Metadata:
{json.dumps(dataset_meta, indent=2)}

EDA & Quality Meta:
{json.dumps(eda_meta, indent=2)}
"""
    if trend_data:
        prompt += f"\nTrend Data:\n{json.dumps(trend_data, indent=2)}"
    if forecast_data:
        prompt += f"\nForecast Data:\n{json.dumps(forecast_data, indent=2)}"
        
    prompt += "\n\nSynthesize this into a structured, professional report following the requested sections. Use HTML formatting with proper headings, tables, and styled elements."
    
    return await _call_gemini(prompt, system_prompt, api_key)
