"use client";

import { useEffect, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Banknote, CheckCircle2, Clock3, ReceiptText, Users } from "lucide-react";
import ChartCard from "../../components/ChartCard";
import KPICard from "../../components/KPICard";
import { ErrorState, LoadingState } from "../../components/PageState";
import { getCategorySales, getCitySales, getMonthlySales, getPaymentMethods, getSummary, getTopProducts } from "../../lib/api";

const colors = ["oklch(0.52 0.19 255)", "oklch(0.62 0.14 190)", "oklch(0.67 0.15 75)", "oklch(0.58 0.16 320)"];
const money = value => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value || 0);

export default function DashboardPage() {
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { Promise.all([getSummary(), getMonthlySales(), getCategorySales(), getCitySales(), getPaymentMethods(), getTopProducts()]).then(([summary, monthly, category, city, payment, products]) => setData({ summary, monthly, category, city, payment, products })).catch(err => setError(err.message)); }, []);
  if (error) return <div className="page-shell"><ErrorState message={`Dashboard could not be loaded: ${error}`} /></div>;
  if (!data) return <div className="page-shell"><LoadingState label="Calculating retail metrics…" /></div>;
  const { summary, monthly, category, city, payment, products } = data;
  return <div className="page-shell"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Sales performance</h1><p className="mt-2 muted">Analytics from every successfully transformed order.</p></div><div className="flex gap-2"><span className="status status-success"><CheckCircle2 size={13} /> {summary.completed_orders} completed</span><span className="status" style={{ background: "oklch(0.95 0.04 75)", color: "oklch(0.42 0.11 75)" }}><Clock3 size={13} /> {summary.pending_orders} pending</span></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><KPICard label="Total revenue" value={money(summary.total_revenue)} detail="After discounts" icon={Banknote} /><KPICard label="Total orders" value={summary.total_orders.toLocaleString()} detail="Unique order IDs" icon={ReceiptText} /><KPICard label="Customers" value={summary.total_customers.toLocaleString()} detail="Unique email keys" icon={Users} /><KPICard label="Average order value" value={money(summary.average_order_value)} detail="Revenue per order" icon={Banknote} /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><ChartCard className="lg:col-span-2" title="Monthly sales trend" description="Revenue by order month"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthly}><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="oklch(0.52 0.19 255)" stopOpacity={.28}/><stop offset="100%" stopColor="oklch(0.52 0.19 255)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="oklch(0.91 0.01 250)" vertical={false}/><XAxis dataKey="month" tickLine={false}/><YAxis tickLine={false} tickFormatter={money}/><Tooltip formatter={value => money(value)}/><Area type="monotone" dataKey="revenue" stroke="oklch(0.52 0.19 255)" strokeWidth={2} fill="url(#salesFill)"/></AreaChart></ResponsiveContainer></ChartCard><RevenueBars title="Sales by category" description="Revenue contribution across merchandise" data={category} keyName="category" /><RevenueBars title="Sales by city" description="Top-performing customer locations" data={city} keyName="city" /><ChartCard title="Payment methods" description="Order distribution by tender"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={payment} dataKey="orders" nameKey="payment_method" innerRadius={65} outerRadius={100} paddingAngle={2}>{payment.map((_, index) => <Cell key={index} fill={colors[index % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></ChartCard><RevenueBars title="Top products" description="Highest revenue products" data={products} keyName="product" horizontal /></div></div>;
}

function RevenueBars({ title, description, data, keyName, horizontal = false }) { return <ChartCard title={title} description={description}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout={horizontal ? "vertical" : "horizontal"} margin={{ left: horizontal ? 30 : 0 }}><CartesianGrid stroke="oklch(0.91 0.01 250)" vertical={!horizontal} horizontal={horizontal}/>{horizontal ? <><XAxis type="number" tickFormatter={money}/><YAxis type="category" dataKey={keyName} width={90} tick={{ fontSize: 11 }}/></> : <><XAxis dataKey={keyName} tickLine={false} tick={{ fontSize: 11 }}/><YAxis tickLine={false} tickFormatter={money}/></>}<Tooltip formatter={value => money(value)}/><Bar dataKey="revenue" fill="oklch(0.52 0.19 255)" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard>; }
